import * as esbuild from 'esbuild'

await esbuild.build({
  entryPoints: ['api/_handler.ts'],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  outfile: 'api/index.js',
  external: [
    'express',
    '@volcengine/rtc',
  ],
  banner: {
    js: "import 'global-agent/bootstrap'; // Auto-generated by scripts/build-api.mjs — do not edit directly",
  },
})

console.log('✅ api/index.js built')
