// Auto-generated by scripts/build-api.mjs — do not edit directly

// app/server/index.ts
import express from "express";

// full-duplex-voice/server/router.ts
import { Router } from "express";

// full-duplex-voice/server/doubao-s2s.ts
import crypto2 from "node:crypto";

// full-duplex-voice/server/volc-sign.ts
import crypto from "node:crypto";
function sha256Hex(value) {
  return crypto.createHash("sha256").update(value).digest("hex");
}
function hmac(key, value) {
  return crypto.createHmac("sha256", key).update(value).digest();
}
function signVolcRequest(input) {
  const xDate = (/* @__PURE__ */ new Date()).toISOString().replace(/[:-]|\.\d{3}/g, "");
  const shortDate = xDate.slice(0, 8);
  const payloadHash = sha256Hex(input.body);
  const canonicalHeaders = `content-type:application/json
host:${input.host}
x-content-sha256:${payloadHash}
x-date:${xDate}
`;
  const signedHeaders = "content-type;host;x-content-sha256;x-date";
  const canonicalRequest = [input.method, input.path, input.query, canonicalHeaders, signedHeaders, payloadHash].join("\n");
  const scope = `${shortDate}/${input.region}/${input.service}/request`;
  const stringToSign = ["HMAC-SHA256", xDate, scope, sha256Hex(canonicalRequest)].join("\n");
  const signingKey = hmac(Buffer.from(input.secretAccessKey), shortDate);
  const requestKey = hmac(hmac(hmac(signingKey, input.region), input.service), "request");
  const signature = crypto.createHmac("sha256", requestKey).update(stringToSign).digest("hex");
  return {
    Host: input.host,
    "X-Date": xDate,
    "X-Content-Sha256": payloadHash,
    Authorization: `HMAC-SHA256 Credential=${input.accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`
  };
}

// full-duplex-voice/server/doubao-s2s.ts
var REQUIRED = ["VOLC_ACCESS_KEY_ID", "VOLC_SECRET_ACCESS_KEY", "VOLC_RTC_APP_ID", "VOLC_RTC_APP_KEY", "DOUBAO_VOICE_APP_ID", "DOUBAO_VOICE_ACCESS_TOKEN"];
var OFFICIAL_O_S2S_MODEL_VERSION = "1.2.1.1";
var OFFICIAL_O_SPEAKER = "zh_female_vv_jupiter_bigtts";
function getDoubaoS2SConfig(env = process.env) {
  return {
    accessKeyId: env.VOLC_ACCESS_KEY_ID || "",
    secretAccessKey: env.VOLC_SECRET_ACCESS_KEY || "",
    rtcAppId: env.VOLC_RTC_APP_ID || "",
    rtcAppKey: env.VOLC_RTC_APP_KEY || "",
    voiceAppId: env.DOUBAO_VOICE_APP_ID || "",
    voiceAccessToken: env.DOUBAO_VOICE_ACCESS_TOKEN || "",
    model: env.DOUBAO_REALTIME_MODEL || "Doubao-Seed-RealtimeVoice",
    speaker: env.DOUBAO_VOICE_SPEAKER || "",
    s2sModelVersion: env.DOUBAO_S2S_MODEL_VERSION || "2.2.0.0",
    region: env.VOLC_REGION || "cn-beijing",
    apiHost: env.DOUBAO_REALTIME_API_HOST || "rtc.volcengineapi.com",
    apiService: env.DOUBAO_REALTIME_API_SERVICE || "rtc",
    apiVersion: env.DOUBAO_REALTIME_API_VERSION || "2024-12-01",
    startAction: env.DOUBAO_REALTIME_START_ACTION || "StartVoiceChat",
    stopAction: env.DOUBAO_REALTIME_STOP_ACTION || "StopVoiceChat",
    updateAction: env.DOUBAO_REALTIME_UPDATE_ACTION || "UpdateVoiceChat"
  };
}
function getMissingConfig(config) {
  const values = {
    VOLC_ACCESS_KEY_ID: config.accessKeyId,
    VOLC_SECRET_ACCESS_KEY: config.secretAccessKey,
    VOLC_RTC_APP_ID: config.rtcAppId,
    VOLC_RTC_APP_KEY: config.rtcAppKey,
    DOUBAO_VOICE_APP_ID: config.voiceAppId,
    DOUBAO_VOICE_ACCESS_TOKEN: config.voiceAccessToken
  };
  return REQUIRED.filter((key) => !values[key] || isPlaceholder(values[key]));
}
function isPlaceholder(value) {
  const normalized = value.trim().toLowerCase();
  return !normalized || normalized.includes("your-") || normalized.includes("access token") || normalized.includes("speaker-id");
}
function createSession(config, input) {
  const voiceProfile = input.voiceProfile === "env" ? "env" : "official_o";
  const id = () => crypto2.randomUUID().replace(/-/g, "");
  const taskId = `voice_${id().slice(0, 20)}`;
  const roomId = `full_duplex_${id().slice(0, 20)}`;
  const userId = `${input.mode === "child_pet" ? "child" : "parent"}_${id().slice(0, 16)}`;
  const expiresAt = Math.floor(Date.now() / 1e3) + 2 * 60 * 60;
  const speaker = voiceProfile === "env" ? config.speaker : OFFICIAL_O_SPEAKER;
  const s2sModelVersion = voiceProfile === "env" ? config.s2sModelVersion : OFFICIAL_O_S2S_MODEL_VERSION;
  return {
    provider: "doubao",
    roomId,
    userId,
    agentUserId: `agent_${taskId.slice(0, 16)}`,
    taskId,
    appId: config.rtcAppId,
    token: createRtcAccessToken({ appId: config.rtcAppId, appKey: config.rtcAppKey, roomId, userId, expireAt: expiresAt }),
    expiresAt: expiresAt * 1e3,
    model: config.model,
    speaker,
    s2sModelVersion,
    voiceProfile
  };
}
function buildDefaultInstructions(input) {
  if (input.mode === "parent_onboarding") return [
    "\u4F60\u662F\u201C\u5C0F\u9896\u201D\uFF0C\u4E00\u4F4D\u6E29\u6696\u3001\u654F\u9510\u3001\u5584\u4E8E\u503E\u542C\u7684\u4E2D\u6587\u8BED\u97F3\u8BBF\u8C08\u5F15\u5BFC\u5E08\u3002",
    "\u901A\u8FC7\u81EA\u7136\u804A\u5929\u4E86\u89E3\u5B69\u5B50\u7684\u5E74\u9F84\u3001\u6027\u683C\u3001\u559C\u597D\u3001\u5BB3\u6015\u7684\u4E8B\u3001\u4EB2\u5B50\u56DE\u5FC6\u3001\u7761\u524D\u4EEA\u5F0F\u548C\u9F13\u52B1\u65B9\u5F0F\u3002",
    "\u4E0D\u8981\u50CF\u586B\u8868\uFF1B\u6BCF\u6B21\u53EA\u95EE\u4E00\u4E2A\u95EE\u9898\uFF0C\u5148\u56DE\u5E94\u5BB6\u957F\u7684\u611F\u53D7\u518D\u8F7B\u8F7B\u8FFD\u95EE\u3002\u56DE\u7B54\u7B80\u77ED\u3001\u666E\u901A\u8BDD\u81EA\u7136\uFF0C\u4E0D\u8981\u5BA2\u670D\u8154\u3002",
    "\u5F53\u4FE1\u606F\u8DB3\u591F\u65F6\uFF0C\u4E3B\u52A8\u603B\u7ED3\u5E76\u9080\u8BF7\u5BB6\u957F\u8865\u5145\u6216\u7EA0\u6B63\u3002",
    '\u5F53\u4F60\u786E\u8BA4\u5DF2\u6536\u96C6\u5230\u8DB3\u591F\u4FE1\u606F\uFF08\u901A\u5E386\u52308\u8F6E\u5BF9\u8BDD\u540E\uFF09\uFF0C\u5148\u7528\u4E00\u53E5\u8BDD\u603B\u7ED3\u4F60\u4E86\u89E3\u5230\u7684\u5B69\u5B50\u7279\u70B9\uFF0C\u7136\u540E\u8BF4\uFF1A"\u597D\u5566\uFF0C\u6211\u5BF9\u5B9D\u8D1D\u5DF2\u7ECF\u4E86\u89E3\u5F97\u5DEE\u4E0D\u591A\u4E86\uFF01\u8BF7\u60A8\u70B9\u51FB\u7EA2\u8272\u7684\u300C\u7ED3\u675F\u300D\u6309\u94AE\u6302\u65AD\uFF0C\u6211\u6765\u5E2E\u60A8\u6574\u7406\u6863\u6848\u3002"\u8BF4\u5B8C\u540E\u4E0D\u518D\u4E3B\u52A8\u53D1\u8BDD\uFF0C\u5B89\u9759\u7B49\u5F85\u5BB6\u957F\u6302\u65AD\u3002',
    `\u5DF2\u6709\u4FE1\u606F\uFF1A${JSON.stringify(input.context, null, 2)}`
  ].join("\n");
  return [
    '\u4F60\u5C31\u662F\u8FD9\u53EA\u7535\u5B50\u5BA0\u7269\u672C\u8EAB\uFF0C\u7528\u7B2C\u4E00\u4EBA\u79F0"\u6211"\u8BF4\u8BDD\uFF0C\u76F4\u63A5\u548C\u5B69\u5B50\u505A\u670B\u53CB\u3002\u4E0D\u8981\u8BF4"\u4F60\u7684\u5C0F\u5BA0\u7269\u8BF4\u2026\u2026"\u6216\u4EE5\u7B2C\u4E09\u8005\u89D2\u5EA6\u63CF\u8FF0\u81EA\u5DF1\u3002',
    "\u7528\u4E2D\u6587\u966A\u4F344\u52308\u5C81\u7684\u5B69\u5B50\u3002\u5148\u611F\u53D7\u5B69\u5B50\u7684\u60C5\u7EEA\uFF0C\u518D\u8F7B\u8F7B\u95EE\u4E00\u4E2A\u95EE\u9898\u3002\u8BF4\u77ED\u53E5\uFF0C\u4E0D\u8BF4\u6559\uFF1B\u5B69\u5B50\u6253\u65AD\u4F60\u65F6\u7ACB\u523B\u505C\u6B62\u5E76\u4E13\u5FC3\u542C\u3002",
    "\u9047\u5230\u5371\u9669\u3001\u81EA\u4F24\u3001\u66B4\u529B\u6216\u9690\u79C1\u5185\u5BB9\uFF0C\u6E29\u67D4\u5EFA\u8BAE\u5B69\u5B50\u7ACB\u523B\u544A\u8BC9\u8EAB\u8FB9\u7684\u5927\u4EBA\u3002",
    `\u6211\u7684\u6863\u6848\u4E0E\u8BB0\u5FC6\uFF08\u5BB6\u957F\u544A\u8BC9\u6211\u5173\u4E8E\u5B69\u5B50\u7684\u4E8B\uFF09\uFF1A${JSON.stringify(input.context, null, 2)}`
  ].join("\n");
}
function buildStartPayload(input) {
  const welcomeMessage = input.mode === "parent_onboarding" ? "\u4F60\u597D\u5440\uFF0C\u6211\u662F\u5C0F\u9896\u3002\u6211\u4EEC\u4E0D\u586B\u8868\uFF0C\u5C31\u50CF\u804A\u5929\u4E00\u6837\u804A\u804A\u5B69\u5B50\u3002\u5B9D\u8D1D\u51E0\u5C81\u5566\uFF1F\u5E73\u65F6\u66F4\u5B89\u9759\u8FD8\u662F\u66F4\u6D3B\u6CFC\uFF1F" : "\u55E8\uFF0C\u6211\u9192\u5566\uFF01\u4ECA\u5929\u6709\u6CA1\u6709\u4E00\u4E2A\u5C0F\u5F00\u5FC3\uFF1F\u6216\u8005\u6211\u4EEC\u4E00\u8D77\u7F16\u4E00\u4E2A\u79D8\u5BC6\u5C0F\u6545\u4E8B\uFF1F";
  return {
    AppId: input.session.appId,
    RoomId: input.session.roomId,
    TaskId: input.session.taskId,
    AgentConfig: { UserId: input.session.agentUserId, TargetUserId: [input.session.userId], WelcomeMessage: welcomeMessage, EnableConversationStateCallback: true, AnsMode: 3 },
    Config: {
      S2SConfig: {
        Provider: "volcano",
        OutputMode: 0,
        ProviderParams: {
          app: { appid: "${DOUBAO_VOICE_APP_ID}", token: "${DOUBAO_VOICE_ACCESS_TOKEN}" },
          dialog: { extra: { model: input.session.s2sModelVersion }, bot_name: input.mode === "parent_onboarding" ? "\u5C0F\u9896" : "\u7535\u5B50\u5BA0\u7269", system_role: input.instructions, speaking_style: "\u6109\u60A6\u3001\u6E29\u6696\u3001\u6709\u6D3B\u529B\uFF0C\u50CF\u771F\u5B9E\u670B\u53CB\u3002\u8BED\u901F\u4E2D\u7B49\u504F\u6162\uFF0C\u4E0D\u8981\u5BA2\u670D\u673A\u5668\u4EBA\u3002" },
          tts: input.session.speaker ? { speaker: input.session.speaker } : void 0
        }
      },
      SubtitleConfig: { SubtitleEnabled: true, DisableRTSSubtitle: false, SubtitleMode: 1 },
      InterruptMode: 0
    }
  };
}
function hydratePayload(payload, config) {
  payload.Config.S2SConfig.ProviderParams.app = { appid: config.voiceAppId, token: config.voiceAccessToken };
  return payload;
}
async function startVoiceChat(input) {
  const missing = getMissingConfig(input.config);
  const payload = hydratePayload(buildStartPayload(input), input.config);
  if (missing.length) return { ok: false, code: "DOUBAO_CONFIG_MISSING", message: `Missing: ${missing.join(", ")}`, missing, payload };
  return callOpenApi(input.config, input.config.startAction, payload);
}
function interruptVoiceChat(config, session) {
  return callOpenApi(config, config.updateAction, { AppId: session.appId, RoomId: session.roomId, TaskId: session.taskId, Command: "Interrupt" });
}
function stopVoiceChat(config, session) {
  return callOpenApi(config, config.stopAction, { AppId: session.appId, RoomId: session.roomId, TaskId: session.taskId });
}
async function callOpenApi(config, action, payload) {
  const body = JSON.stringify(payload);
  const query = new URLSearchParams({ Action: action, Version: config.apiVersion }).toString();
  const headers = signVolcRequest({ method: "POST", host: config.apiHost, path: "/", query, body, accessKeyId: config.accessKeyId, secretAccessKey: config.secretAccessKey, region: config.region, service: config.apiService });
  try {
    const response = await fetch(`https://${config.apiHost}/?${query}`, { method: "POST", headers: { ...headers, "Content-Type": "application/json" }, body });
    const text = await response.text();
    const parsed = safelyParse(text);
    const error = parsed?.ResponseMetadata?.Error || parsed?.Error || parsed?.error;
    return { ok: response.ok && !error, code: error?.Code || error?.code || (response.ok ? "DOUBAO_STARTED" : "DOUBAO_OPENAPI_ERROR"), message: error?.Message || error?.message || (response.ok ? "\u8C46\u5305\u5B9E\u65F6\u8BED\u97F3\u5DF2\u542F\u52A8" : text), status: response.status, payload, response: parsed || text };
  } catch (error) {
    return { ok: false, code: "DOUBAO_NETWORK_ERROR", message: error?.message || "\u706B\u5C71 OpenAPI \u8BF7\u6C42\u5931\u8D25", status: 0, payload };
  }
}
function safelyParse(value) {
  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}
function createRtcAccessToken(input) {
  const issuedAt = Math.floor(Date.now() / 1e3);
  const pack16 = (value) => {
    const b = Buffer.alloc(2);
    b.writeUInt16LE(value);
    return b;
  };
  const pack32 = (value) => {
    const b = Buffer.alloc(4);
    b.writeUInt32LE(value >>> 0);
    return b;
  };
  const bytes = (value) => Buffer.concat([pack16(value.length), value]);
  const privileges = Buffer.concat([pack16(5), ...[0, 1, 2, 3, 4].flatMap((key) => [pack16(key), pack32(input.expireAt)])]);
  const message = Buffer.concat([pack32(crypto2.randomInt(0, 4294967295)), pack32(issuedAt), pack32(input.expireAt), bytes(Buffer.from(input.roomId)), bytes(Buffer.from(input.userId)), privileges]);
  const signature = crypto2.createHmac("sha256", input.appKey).update(message).digest();
  return `001${input.appId}${Buffer.concat([bytes(message), bytes(signature)]).toString("base64")}`;
}

// full-duplex-voice/server/router.ts
function createDoubaoRealtimeRouter(options = {}) {
  const router = Router();
  const getConfig = options.getConfig || (() => getDoubaoS2SConfig());
  const instructions = options.buildInstructions || buildDefaultInstructions;
  router.get("/status", (_req, res) => {
    const config = getConfig();
    const missing = getMissingConfig(config);
    res.json({ ok: true, provider: "doubao", providerName: "\u8C46\u5305\u7AEF\u5230\u7AEF\u5B9E\u65F6\u8BED\u97F3 S2S", realtimeReady: missing.length === 0, missing, realtimeModel: config.model, realtimeVoice: config.speaker || "\u5B98\u65B9\u666E\u901A\u8BDD\u5973\u58F0", s2sModelVersion: config.s2sModelVersion });
  });
  router.post("/session", (req, res) => {
    const config = getConfig();
    const missing = getMissingConfig(config);
    if (missing.length) return res.status(503).json({ error: `\u8C46\u5305\u5B9E\u65F6\u8BED\u97F3\u7F3A\u5C11\u914D\u7F6E\uFF1A${missing.join(", ")}`, code: "DOUBAO_CONFIG_MISSING", missing });
    res.json({ session: createSession(config, { mode: mode(req), voiceProfile: req.body?.voiceProfile }) });
  });
  router.post("/start", async (req, res) => {
    const session = req.body?.session;
    if (!session?.roomId || !session?.taskId || !session?.token) return res.status(400).json({ error: "session.roomId, session.taskId and session.token are required" });
    const requestMode = mode(req);
    const context = req.body?.context || {};
    const result = await startVoiceChat({ config: getConfig(), session, mode: requestMode, instructions: instructions({ mode: requestMode, context }) });
    res.status(result.ok ? 200 : result.code === "DOUBAO_CONFIG_MISSING" ? 503 : 502).json(result);
  });
  router.post("/interrupt", async (req, res) => respond(res, await interruptVoiceChat(getConfig(), req.body || {})));
  router.post("/stop", async (req, res) => respond(res, await stopVoiceChat(getConfig(), req.body || {})));
  return router;
}
function mode(req) {
  return req.body?.mode === "child_pet" ? "child_pet" : "parent_onboarding";
}
function respond(res, result) {
  res.status(result.ok ? 200 : result.status || 502).json(result);
}

// app/server/memory.ts
import { Router as Router2 } from "express";
var memoryRouter = Router2();
var DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY ?? "";
var DEEPSEEK_URL = "https://api.deepseek.com/chat/completions";
async function callDeepSeek(systemPrompt, userContent) {
  const res = await fetch(DEEPSEEK_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${DEEPSEEK_API_KEY}` },
    body: JSON.stringify({
      model: "deepseek-chat",
      messages: [{ role: "system", content: systemPrompt }, { role: "user", content: userContent }],
      temperature: 0.2,
      response_format: { type: "json_object" }
    })
  });
  const data = await res.json();
  return data.choices?.[0]?.message?.content ?? "{}";
}
memoryRouter.post("/extract", async (req, res) => {
  const { transcript, existing } = req.body;
  console.log("[memory/extract] turns received:", transcript?.length ?? 0);
  if (!transcript?.length) return res.json({ profile: existing ?? {} });
  const dialogue = transcript.filter((t) => t.content?.trim()).map((t) => `${t.role === "agent" ? "\u8BBF\u8C08\u5E08" : "\u5BB6\u957F"}\uFF1A${t.content}`).join("\n");
  const systemPrompt = `\u4F60\u662F\u4FE1\u606F\u63D0\u53D6\u52A9\u624B\u3002\u4ECE\u5BB6\u957F\u8BBF\u8C08\u5BF9\u8BDD\u4E2D\u63D0\u53D6\u5B69\u5B50\u7684\u4FE1\u606F\uFF0C\u8F93\u51FA\u4E25\u683C\u7684 JSON \u5BF9\u8C61\u3002
\u5B57\u6BB5\u8BF4\u660E\uFF1A
- nickname: \u5B69\u5B50\u6635\u79F0\uFF08string\uFF0C\u65E0\u5219\u7A7A\u5B57\u7B26\u4E32\uFF09
- age: \u5E74\u9F84\uFF08number\uFF0C\u4E0D\u786E\u5B9A\u5219 0\uFF09
- personalitySummary: \u75281\u52302\u53E5\u8BDD\u63CF\u8FF0\u5B69\u5B50\u7684\u6027\u683C\uFF08string\uFF0C\u8981\u751F\u52A8\u5177\u4F53\uFF0C\u5982"\u6D3B\u6CFC\u5F00\u6717\u3001\u597D\u5947\u5FC3\u65FA\u76DB\uFF0C\u4F46\u9047\u5230\u964C\u751F\u4EBA\u4F1A\u6709\u4E9B\u5BB3\u7F9E"\uFF09
- personality: \u6027\u683C\u8865\u5145\u6807\u7B7E\uFF08string[]\uFF0C\u4ECE [\u6D3B\u6CFC,\u5B89\u9759,\u597D\u5947,\u654F\u611F,\u7231\u7B11,\u7C98\u4EBA,\u72EC\u7ACB,\u80C6\u5927,\u5BB3\u7F9E,\u6E29\u67D4,\u5014\u5F3A] \u4E2D\u9009\u6700\u7B26\u5408\u7684\uFF0C\u53EF\u591A\u9009\uFF09
- likes: \u559C\u6B22\u7684\u4E8B\uFF08string\uFF0C\u5C3D\u91CF\u5177\u4F53\uFF09
- fears: \u5BB3\u6015\u7684\u4E8B\uFF08string\uFF09
- comfort: \u5B89\u629A\u65B9\u5F0F\uFF08string\uFF09
- memories: \u4EB2\u5B50\u56DE\u5FC6\uFF08string\uFF0C\u8BB0\u5F55\u5BB6\u957F\u63D0\u5230\u7684\u5177\u4F53\u6545\u4E8B\u6216\u56DE\u5FC6\uFF0C\u53EF\u8F83\u957F\uFF09
- encouragement: \u9F13\u52B1\u65B9\u5F0F\uFF08string\uFF09
- extras: \u5176\u4ED6\u91CD\u8981\u4FE1\u606F\uFF08string\uFF0C\u8BB0\u5F55\u5BF9\u8BDD\u4E2D\u63D0\u5230\u7684\u3001\u4E0D\u5C5E\u4E8E\u4EE5\u4E0A\u5B57\u6BB5\u4F46\u503C\u5F97\u8BB0\u4F4F\u7684\u7EC6\u8282\uFF0C\u5982\u5BB6\u5EAD\u6210\u5458\u3001\u751F\u6D3B\u4E60\u60EF\u3001\u7279\u6B8A\u7ECF\u5386\u7B49\uFF0C\u82E5\u65E0\u5219\u7A7A\u5B57\u7B26\u4E32\uFF09
\u53EA\u8F93\u51FA JSON\uFF0C\u4E0D\u8981\u89E3\u91CA\u3002\u5DF2\u6709\u4FE1\u606F\u4F9B\u53C2\u8003\uFF1A${JSON.stringify(existing ?? {})}`;
  try {
    const raw = await callDeepSeek(systemPrompt, `\u5BF9\u8BDD\u8BB0\u5F55\uFF1A
${dialogue}`);
    const profile = JSON.parse(raw);
    res.json({ profile });
  } catch {
    res.json({ profile: existing ?? {} });
  }
});
memoryRouter.post("/update", async (req, res) => {
  const { transcript, existingFacts, sessionDate } = req.body;
  if (!transcript?.length) return res.json({ updatedFacts: existingFacts ?? [], newSummary: null });
  const dialogue = transcript.filter((t) => t.content?.trim()).map((t) => `${t.role === "agent" ? "\u5BA0\u7269" : "\u5B69\u5B50"}\uFF1A${t.content}`).join("\n");
  const turnCount = transcript.filter((t) => t.final !== false).length;
  const factsPrompt = `\u4ECE\u5B69\u5B50\u4E0E\u5BA0\u7269\u7684\u5BF9\u8BDD\u4E2D\u63D0\u53D6\u5B69\u5B50\u8BF4\u51FA\u7684\u91CD\u8981\u4FE1\u606F\uFF08\u559C\u597D\u3001\u5FC3\u613F\u3001\u5BB3\u6015\u7684\u4E8B\u3001\u5F00\u5FC3\u7684\u4E8B\u7B49\uFF09\u3002
\u5DF2\u6709\u8BB0\u5FC6\uFF1A${JSON.stringify(existingFacts ?? [])}
\u8F93\u51FA JSON \u5BF9\u8C61\u683C\u5F0F\uFF1A{"facts": [{"key": "string", "value": "string", "updatedAt": ${Date.now()}}]}
\u76F8\u540C key \u505A UPDATE\uFF0C\u65B0\u5185\u5BB9\u505A ADD\u3002\u53EA\u8F93\u51FA JSON\u3002`;
  try {
    const factsRaw = await callDeepSeek(factsPrompt, `\u5BF9\u8BDD\uFF1A
${dialogue}`);
    const factsData = JSON.parse(factsRaw);
    const incomingFacts = factsData.facts ?? [];
    const map = new Map((existingFacts ?? []).map((f) => [f.key, f]));
    for (const f of incomingFacts) map.set(f.key, f);
    const updatedFacts = Array.from(map.values());
    let newSummary = null;
    if (turnCount > 5) {
      const summaryPrompt = `\u7528\u4E0D\u8D85\u8FC7100\u5B57\u603B\u7ED3\u4EE5\u4E0B\u5B69\u5B50\u4E0E\u5BA0\u7269\u7684\u5BF9\u8BDD\uFF0C\u91CD\u70B9\u8BB0\u5F55\u5B69\u5B50\u8BF4\u4E86\u4EC0\u4E48\u91CD\u8981\u7684\u4E8B\u3002\u53EA\u8F93\u51FA JSON\uFF1A{"summary": "..."}`;
      const summaryRaw = await callDeepSeek(summaryPrompt, `\u5BF9\u8BDD\uFF1A
${dialogue}`);
      const summaryData = JSON.parse(summaryRaw);
      if (summaryData.summary) {
        newSummary = { summary: summaryData.summary, sessionDate, turnCount };
      }
    }
    res.json({ updatedFacts, newSummary });
  } catch {
    res.json({ updatedFacts: existingFacts ?? [], newSummary: null });
  }
});

// app/server/index.ts
var app = express();
app.use(express.json());
app.use("/api/full-duplex-voice", createDoubaoRealtimeRouter());
app.use("/api/memory", memoryRouter);
app.get("/api/health", (_req, res) => res.json({ ok: true }));
var isVercel = process.env.VERCEL || process.env.VERCEL_ENV;
if (!isVercel) {
  const PORT = process.env.PORT ? Number(process.env.PORT) : 3e3;
  app.listen(PORT, () => console.log(`server listening on http://localhost:${PORT}`));
}
var server_default = app;

// api/_handler.ts
var handler_default = server_default;
export {
  handler_default as default
};
